---
title: "RepDataProject2"
author: "Shimon Yannay"
date: "2019 M02 28"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
```

# Reproducible Research - Project1

## Across the United States, which types of events (as indicated in the \color{red}{\verb|EVTYPE|}EVTYPE variable) are most harmful with respect to population health?

### Data Processing


```{r, echo=TRUE}
options(warn=-1)
data <- read.csv("repdata_data_StormData.csv")
```

### Gathering relevant data from all

```{r, echo=TRUE}
sub_data <- data[,c("EVTYPE","FATALITIES","INJURIES", "PROPDMG","PROPDMGEXP","CROPDMG","CROPDMGEXP")]
sub_data$PROPDMGEXP <- as.character(sub_data$PROPDMGEXP)
sub_data$CROPDMGEXP <- as.character(sub_data$CROPDMGEXP)
agg_fat <- aggregate(sub_data$FATALITIES,by=list(sub_data$EVTYPE), sum)
agg_inj <- aggregate(sub_data$INJURIES,by=list(sub_data$EVTYPE), sum)
```
## Results

### Most fatal events
```{r}
## order by fatalities
agg_fat_ord <- agg_fat[order(agg_fat$x, decreasing = T), ]
## order by injuries
agg_inj_ord <- agg_inj[order(agg_inj$x, decreasing = T), ]
## Head of ordered by fatalities
head_fatal <- head(agg_fat_ord)
names(head_fatal) <- c("Event", "Fatalities")
head_fatal

p1 <- ggplot(data=head_fatal, mapping=aes(x=head_fatal$Event, y=head_fatal$Fatalities))+geom_bar(stat="identity")+xlab("Event")+ylab("Fatalities")
print(p1)

## Head of ordered by injuries
head_injury <- head(agg_inj_ord)
names(head_injury) <- c("Event", "Injuries")
head_injury
p1 <- ggplot(data=head_injury, mapping=aes(x=head_injury$Event, y=head_injury$Injuries))+geom_bar(stat="identity")+xlab("Event")+ylab("Injuries")
print(p1)
```
## Across the United States, which types of events have the greatest economic consequences?

```{r}
## calculate the exponent of damage costs
getE <- function(char) {
  options(warn=-1)
    if (char %in% c("h", "H"))
        return(2)
    else if (char %in% c("k", "K"))
        return(3)
    else if (char %in% c("m", "M"))
        return(6)
    else if (char %in% c("b", "B"))
        return(9)
    else if (!is.na(as.numeric(char))) 
        return(as.numeric(char))
    else return(0)
}
## Damaged caused to property
sub_data$dmg_prop <- sub_data$PROPDMG * 10**getE(sub_data$PROPDMGEXP)

agg_dmg_prop <- aggregate(sub_data$dmg_prop,by=list(sub_data$EVTYPE), sum)

agg_dmg_prop_ord <- agg_dmg_prop[order(agg_dmg_prop$x, decreasing = T), ]

head_dmg_prop <- head(agg_dmg_prop_ord)
names(head_dmg_prop) <- c("Event", "PropertyDamage")
head_dmg_prop

p1 <- ggplot(data=head_dmg_prop, mapping=aes(x=head_dmg_prop$Event, y=head_dmg_prop$PropertyDamage))+geom_bar(stat="identity")+xlab("Event")+ylab("Property Damage")
print(p1)

## Damage caused to crop
sub_data$dmg_crop <- sub_data$CROPDMG * 10**getE(sub_data$CROPDMGEXP)

agg_dmg_crop <- aggregate(sub_data$dmg_crop,by=list(sub_data$EVTYPE), sum)

agg_dmg_crop_ord <- agg_dmg_crop[order(agg_dmg_crop$x, decreasing = T), ]

head_dmg_crop <- head(agg_dmg_crop_ord)
names(head_dmg_crop) <- c("Event", "CropDamage")
head_dmg_crop

p1 <- ggplot(data=head_dmg_crop, mapping=aes(x=head_dmg_crop$Event, y=head_dmg_crop$CropDamage))+geom_bar(stat="identity")+xlab("Event")+ylab("Crop Damage")
print(p1)
## Add data to calculate damage caused to Property and Crop
sub_data$economyDMG <- sub_data$dmg_prop + sub_data$dmg_crop

agg_eco <- aggregate(sub_data$economyDMG,by=list(sub_data$EVTYPE), sum)
## order by damage
agg_eco_ord <- agg_eco[order(agg_eco$x, decreasing = T), ]
## Head of ordered by damage costs
head_eco_ord <- head(agg_eco_ord)

names(head_eco_ord) <- c("Event", "TotalEconomyDamage")
head_eco_ord

p1 <- ggplot(data=head_eco_ord, mapping=aes(x=head_eco_ord$Event, y=head_eco_ord$TotalEconomyDamage))+geom_bar(stat="identity")+xlab("Event")+ylab("Total Economy Damage")
print(p1)
```
